version: '3.8'

services:
  besu-permissioning-dashboard:
    image: cupcakearmy/static
    container_name: besu-permissioning-dashboard
    restart: unless-stopped
    volumes:
      - ./dist/app:/srv:ro
    ports:
      - 3000:80
